# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"chrome_options": "00_images.ipynb",
         "get_browser_page": "00_images.ipynb",
         "DDG_SEARCH_URL": "00_images.ipynb",
         "extract_images": "00_images.ipynb",
         "extract_url": "00_images.ipynb",
         "extract_img_urls": "00_images.ipynb",
         "DATA_SRC_URL_PATTERN": "00_images.ipynb",
         "get_image_urls": "00_images.ipynb",
         "download_search_urls": "00_images.ipynb",
         "download_image_inner": "00_images.ipynb",
         "download_images_slowly": "00_images.ipynb",
         "download_search_images_slowly": "00_images.ipynb"}

modules = ["images.py"]

doc_url = "https://butchland.github.io/ddg_images_downloader/"

git_url = "https://github.com/butchland/ddg_images_downloader/tree/master/"

def custom_doc_links(name): return None
